### ISSUE TITLE
Doubts in installation

### ISSUE THREAD

**Issue by pdechery** [Cybolic/LinReaper#6]
Hi,

Sorry for the possible dumb question but in the Installation part of the README which is exactly the file you ask to be run? I suppose it is **main.py** but I'm not sure.

Also, I have a fresh Ubuntu 16.04 (64 bits) install but I don't have PyGTK. I went to the site to download it but I found very difficult to understand how it's done. Even using Ubuntu for a year now the part of software installation is pretty hard to get for me.

I will continue to try having Reaper on my Ubuntu. Thanks for your tool, it seems very promising.

**Comment by Cybolic** [comment]
Sorry about the confusion. The README was copied from the original Cockos forum, where this code is distributed as a file that you simply double click, but yes, running main.py accomplishes the same thing.

As for PyGTK, you can install it much like any other software in Linux, using the package manager. Either find it in the Software Boutique (or your preferred graphical tool for the job) or by running the following command:

```
sudo apt install python-gtk2
```

No need to go to any websites :)

**Comment by pdechery** [comment]
Awesome, thank you!
